export enum Manufacturers {
  AEROSPATIALE = 'AEROSPATIALE',
  AIRBUS = 'AIRBUS',
  ATR = 'ATR',
  BAE_SYSTEMS = 'BAE_SYSTEMS',
  BOEING = 'BOEING',
  BOMBARDIER = 'BOMBARDIER',
  DIRGANTARA_INDONESIA = 'DIRGANTARA_INDONESIA',
  EMBRAER = 'EMBRAER',
  FOKKER = 'FOKKER',
  ILYUSHIN = 'ILYUSHIN',
  SAAB = 'SAAB',
  SUKHOI = 'SUKHOI',
  TUPOLEV = 'TUPOLEV'
}
